version: '3.8'
services:
  mongodb:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongo
      MONGO_INITDB_ROOT_PASSWORD: mongo
      MONGO_INITDB_DATABASE: face_auth_db
    ports:
      - "27017:27017"
    volumes:
      - mongodbv:/data/db
volumes:
  mongodbv:
